name: Deploy to GitHub Pages
on:
  push:
    siteurl: "https://catkhakis.github.io/zoeySite/"
    branches: ["main"]
  workflow_dispatch:
jobs:
  deploy:
    uses: "getpelican/pelican/.github/workflows/github_pages.yml@main"
    permissions:
      contents: "read"
      pages: "write"
      id-token: "write"
    with:
      settings: "publishconf.py"
      requirements: "pelican[markdown] typogrify lucide pelican-webassets cssmin rjsmin pelican-jinja2content"